-- ===========================================================================
-- Networking Tracker — contacts table, constraints, and Row Level Security
-- ===========================================================================
-- Run this in the Neon Console SQL Editor.
--
-- AFTER RUNNING THIS: go to the Data API page in the Neon Console and click
-- "Refresh schema cache". The Data API caches your table definitions, so a
-- brand new table returns 404 until the cache is refreshed. This catches
-- everyone once.
-- ===========================================================================


-- ---------------------------------------------------------------------------
-- 1. The table
-- ---------------------------------------------------------------------------
CREATE TABLE contacts (
  id                bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

  -- Ownership. auth.user_id() returns the "sub" claim of the signed-in user's
  -- JWT as text. Because it is a DEFAULT, the client never sends this value --
  -- the database stamps it. Because it is NOT NULL, a row can never exist
  -- without an owner.
  user_id           text NOT NULL DEFAULT (auth.user_id()),

  -- Required by the assignment ---------------------------------------------
  name              text NOT NULL CHECK (length(trim(name)) > 0),
  company           text CHECK (company   IS NULL OR length(company)   <= 200),
  role              text CHECK (role      IS NULL OR length(role)      <= 200),
  where_met         text CHECK (where_met IS NULL OR length(where_met) <= 200),
  notes             text CHECK (notes     IS NULL OR length(notes)     <= 5000),

  -- Priority accepts only these three values, enforced by the database itself.
  priority          text NOT NULL DEFAULT 'medium'
                    CHECK (priority IN ('high', 'medium', 'low')),

  -- Follow-up cadence ------------------------------------------------------
  -- When you last spoke, and how often you want to stay in touch. The app
  -- derives "who to reach out to this week" from these two columns; nothing
  -- about the schedule is stored, so there is nothing to keep in sync.
  last_contacted_on date CHECK (last_contacted_on IS NULL
                                OR last_contacted_on >= DATE '1900-01-01'),

  cadence           text NOT NULL DEFAULT 'quarterly'
                    CHECK (cadence IN ('monthly', 'quarterly', 'annually', 'custom')),

  -- Only used when cadence = 'custom'.
  cadence_days      integer CHECK (cadence_days IS NULL
                                   OR cadence_days BETWEEN 1 AND 3650),

  created_at        timestamptz NOT NULL DEFAULT now(),
  updated_at        timestamptz NOT NULL DEFAULT now(),

  -- cadence_days must be present for 'custom' and absent otherwise.
  -- Comparing two booleans with = is a readable way to say "these must agree".
  CONSTRAINT cadence_days_only_when_custom
    CHECK ((cadence = 'custom') = (cadence_days IS NOT NULL))
);

-- Fast lookup of one user's contacts.
CREATE INDEX contacts_user_id_idx ON contacts (user_id);

COMMENT ON COLUMN contacts.user_id IS
  'Owner. Defaults to auth.user_id() (the JWT sub claim). Never sent by the client.';


-- ---------------------------------------------------------------------------
-- 2. Keep updated_at honest
-- ---------------------------------------------------------------------------
-- Without this, a client could send any updated_at it liked.
CREATE OR REPLACE FUNCTION set_updated_at()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
  NEW.updated_at := now();
  -- Ownership is immutable: an edit can never change who owns a row.
  NEW.user_id    := OLD.user_id;
  RETURN NEW;
END;
$$;

CREATE TRIGGER contacts_set_updated_at
  BEFORE UPDATE ON contacts
  FOR EACH ROW
  EXECUTE FUNCTION set_updated_at();


-- ---------------------------------------------------------------------------
-- 3. Row Level Security
-- ---------------------------------------------------------------------------
-- Three possible states, worth knowing:
--   RLS disabled            -> every authenticated user sees every row
--   RLS enabled, no policy  -> nobody sees anything (default deny)
--   RLS enabled + policies  -> rows filtered by the policy rules
--
-- So enabling RLS is the safe default: it denies everything until we
-- explicitly grant access below.
ALTER TABLE contacts ENABLE ROW LEVEL SECURITY;

-- A separate policy per operation, as the assignment requires.
--
-- USING      = which existing rows this operation may see or touch
-- WITH CHECK = what a row is allowed to look like after being written
--
-- (select auth.user_id()) is wrapped in a subselect so Postgres evaluates it
-- once per query instead of once per row.

CREATE POLICY contacts_select_own ON contacts
  FOR SELECT TO authenticated
  USING ( (select auth.user_id()) = user_id );

CREATE POLICY contacts_insert_own ON contacts
  FOR INSERT TO authenticated
  WITH CHECK ( (select auth.user_id()) = user_id );

-- Both clauses matter here:
--   USING      stops you editing someone else's row
--   WITH CHECK stops you rewriting your own row to belong to someone else
CREATE POLICY contacts_update_own ON contacts
  FOR UPDATE TO authenticated
  USING      ( (select auth.user_id()) = user_id )
  WITH CHECK ( (select auth.user_id()) = user_id );

CREATE POLICY contacts_delete_own ON contacts
  FOR DELETE TO authenticated
  USING ( (select auth.user_id()) = user_id );


-- ---------------------------------------------------------------------------
-- 4. Table privileges
-- ---------------------------------------------------------------------------
-- RLS filters rows; privileges decide whether the role may touch the table at
-- all. Both are needed. Skip this block if you ticked "Grant public schema
-- access" when enabling the Data API -- Neon will have run the equivalent.
--
-- Note "anonymous" is granted nothing: a request with no valid token gets that
-- role and can read nothing.
GRANT USAGE ON SCHEMA public TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON contacts TO authenticated;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO authenticated;


-- ---------------------------------------------------------------------------
-- 5. Verify it worked
-- ---------------------------------------------------------------------------
-- Expect: rowsecurity = true, and four policies.

-- SELECT relname, relrowsecurity FROM pg_class WHERE relname = 'contacts';
-- SELECT policyname, cmd, qual, with_check FROM pg_policies WHERE tablename = 'contacts';
